import { PhysicalConstants } from './types';

export const INITIAL_CONSTANTS: PhysicalConstants = {
  speedOfLight: {
    id: 'speedOfLight',
    description: "The maximum speed at which all matter and information in the universe can travel.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  gravitationalConstant: {
    id: 'gravitationalConstant',
    description: "Determines the strength of the gravitational force between objects.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  planckConstant: {
    id: 'planckConstant',
    description: "A fundamental constant in quantum mechanics, relating a particle's energy to its frequency.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  elementaryCharge: {
    id: 'elementaryCharge',
    description: "The magnitude of the electric charge carried by a single proton or electron.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  fineStructureConstant: {
    id: 'fineStructureConstant',
    description: "Characterizes the strength of the electromagnetic interaction between charged particles.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  cosmologicalConstant: {
    id: 'cosmologicalConstant',
    description: "Represents the energy density of empty space, affecting the expansion of the universe.",
    value: 1.0,
    min: -5.0,
    max: 5.0,
    step: 0.1,
  },
  strongNuclearForce: {
    id: 'strongNuclearForce',
    description: "Binds protons and neutrons together to form atomic nuclei.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  weakNuclearForce: {
    id: 'weakNuclearForce',
    description: "Responsible for radioactive decay and nuclear fusion.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
  higgsFieldStrength: {
    id: 'higgsFieldStrength',
    description: "Gives mass to elementary particles through the Higgs mechanism.",
    value: 1.0,
    min: 0.1,
    max: 10.0,
    step: 0.1,
  },
};